version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bluegreen
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/bluegreen
      CORS_ORIGIN: http://localhost:3000
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-blue:
    build:
      context: ./frontend-blue
      args:
        VITE_API_BASE_URL: http://localhost:5000
    container_name: frontend-blue
    environment: {}
    ports:
      - "3000:80"
    depends_on:
      - backend

  frontend-green:
    build:
      context: ./frontend-green
      args:
        VITE_API_BASE_URL: http://localhost:5000
    container_name: frontend-green
    environment: {}
    ports:
      - "3001:80"
    depends_on:
      - backend